[tool.poetry]
name = "hass-oidc"
version = "0.1.0"
description = ""
authors = ["Christiaan Goossens <contact@christiaangoossens.nl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.*"

[tool.poetry.dev-dependencies]
homeassistant = "^2022.11.4"
pylint = "^2.15.6"